### PR TITLE
Update DesignDocument#equals to include indexes

### LINKED ISSUE #212: DesignDocument.equals(..) true when design documents differs by indexes
CloudantClient version: 2.2
Java version: 7

DesignDocument doesn't get updated when called DocumentManager.put(..). 
After inspecting the code, it seems that DesignDocument.equals(..) doesn't consider indexes in detecting whether two documents are same. Note that design document are different in-terms of indexes.

Response response = db.getDesignDocumentManager().put(newDesignDoc);

### PR DESCRIPTION
**Pull request by rhyshort**
## What

Correct Issue where ddocs would not be updated if only the `indexes` field had changed.

## How

Regenerate DesignDocument#equals and DesignDocument#hashCode to take
account of the indexes field.

## Testing

New tests added for the `DesignDocument.equals` method in `DesignDocumentTest`, and a test which updates the `indexes` field of a ddoc and saves to the server in `DesignDocumentsTest`.

## Reviewers
reviewer @ricellis 

## Issues

Fixes #212

### CODE REVIEW

**Comment by ricellis** [comment]
`hashCode()` and `equals()` are no longer consistent, you need to update `hashCode()` with `indexes` as well.

**Comment by rhyshort** [comment]
@ricellis done in 666d0ec

**Comment by ricellis** [comment]
There was a lot of duplication in the new equality tests, so I parameterized them in 5424985.

**Comment by ricellis** [comment]
+1

**Pull request merged**
