### PR TITLE
Added support for use_index option

### PR DESCRIPTION
**Pull request by ricellis**
*What*
Add support for the Cloudant Query use_index option.

*How*
Add new getters/setters to FindByIndexOptions and append new option to body of `/db/_find` request

*Testing*
Added use of new options in IndexTests.indexTestsAll()

reviewer @rhyshort 
reviewer @emlaver

### CODE REVIEW

**Comment by rhyshort** [comment]
I'd like to see a test, just so we know in the future we don't break anything

**Comment by ricellis** [comment]
Added tests in 772e5c0

**Comment by rhyshort** [comment]
+1 LGTM

**Comment by emlaver** [comment]
+1

**Pull request merged**
