### PR TITLE
Improve the javadoc for queryView

### PR DESCRIPTION
**Pull request by emlaver**
*What*
Improve the javadoc for ```com.cloudant.client.api.View.queryView```: https://github.com/cloudant/java-cloudant/issues/36

*How*
Add details and sample code for map function, JSON document result, and ViewResult use case.
Update descriptions for parameters and how they relate to the View.

*Testing*
No tests required.

reviewer @ricellis 
reviewer @mikerhodes

### CODE REVIEW

**Comment by emlaver** [comment]
@ricellis Thank you for fixing up the sample code and clarifying key-value pairs.

**Comment by ricellis** [comment]
Might need some more html formatting, like `<P>...</P>` blocks to keep it legible in the generated javadoc as the line breaks won't be included.

**Comment by ricellis** [comment]
Suggest running `./gradlew javadoc` to validate that there are no other warnings or errors after making changes.

**Comment by ricellis** [comment]
+1

**Comment by mikerhodes** [comment]
+1

**Pull request merged**
